# Generated by Django 5.2.5 on 2025-08-20 22:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('mission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID миссии')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reward_exp', models.IntegerField(verbose_name='Награда (опыт)')),
                ('reward_coins', models.IntegerField(verbose_name='Награда (монеты)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Новичок'), (2, 'Продвинутый'), (3, 'Эксперт')], default=1, verbose_name='Уровень сложности')),
                ('required_tasks', models.IntegerField(default=1, verbose_name='Требуемое количество заданий')),
            ],
            options={
                'verbose_name': 'Миссия',
                'verbose_name_plural': 'Миссии',
                'db_table': 'missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID задания')),
                ('type', models.CharField(choices=[('multiple_choice', 'Множественный выбор'), ('true_false', 'Верно/Неверно'), ('fill_blank', 'Заполнить пропуск'), ('matching', 'Сопоставление'), ('essay', 'Эссе')], max_length=20, verbose_name='Тип задания')),
                ('difficulty', models.IntegerField(choices=[(1, 'Легкий'), (2, 'Средний'), (3, 'Сложный')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Сложность')),
                ('content', models.TextField(verbose_name='Содержание задания')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('subject', models.CharField(default='russian', max_length=50, verbose_name='Предмет')),
                ('grade_level', models.IntegerField(default=4, verbose_name='Класс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Согласие получено')),
                ('experience_points', models.IntegerField(default=0, verbose_name='Очки опыта')),
                ('coins', models.IntegerField(default=0, verbose_name='Монеты')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTaskAttempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID попытки')),
                ('selected_answer', models.TextField(verbose_name='Выбранный ответ')),
                ('is_correct', models.BooleanField(verbose_name='Правильно')),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время попытки')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка выполнения',
                'verbose_name_plural': 'Попытки выполнения',
                'db_table': 'user_task_attempts',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.mission', verbose_name='Миссия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Миссия пользователя',
                'verbose_name_plural': 'Миссии пользователей',
                'db_table': 'user_missions',
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
