# Generated by Django 5.2.5 on 2025-08-21 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subjects/', verbose_name='Картинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='usertaskattempt',
            options={'ordering': ['-attempt_time'], 'verbose_name': 'История решения', 'verbose_name_plural': 'История решений'},
        ),
        migrations.RemoveField(
            model_name='mission',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='required_tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_class',
            field=models.CharField(default='4', help_text='В каком классе учится', max_length=10, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(verbose_name='Описание миссии'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название миссии'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Задание_4', 'Задание 4 класса'), ('Задание_5', 'Задание 5 класса'), ('Задание_6', 'Задание 6 класса'), ('Задание_7', 'Задание 7 класса'), ('Задание_8', 'Задание 8 класса'), ('Задание_9', 'Задание 9 класса'), ('Задание_10', 'Задание 10 класса'), ('Задание_11', 'Задание 11 класса')], max_length=20, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку данных'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID пользователя'),
        ),
        migrations.AlterField(
            model_name='usertaskattempt',
            name='is_correct',
            field=models.BooleanField(verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.subject', verbose_name='Предмет'),
        ),
        migrations.CreateModel(
            name='UserMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake_text', models.TextField(verbose_name='Текст ошибки')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('user_answer', models.TextField(verbose_name='Ответ пользователя')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата ошибки')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ошибка пользователя',
                'verbose_name_plural': 'Ошибки пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
