# Generated by Django 5.2.5 on 2025-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_subject_alter_usertaskattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(help_text='Например: Задание_4, Задание_7, ЕГЭ_1, ОГЭ_15, и т.д.', max_length=50, verbose_name='Тип задания'),
        ),
    ]
