# Generated by Django 4.2.23 on 2025-08-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_alter_task_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
    ]
